---
title: "Reading Data From the Web"
author: "Jiajun Tao"
date: "2022-10-13"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(rvest)
library(httr)





knitr::opts_chunk$set(echo = TRUE)
```

```{r}
url = "http://samhda.s3-us-gov-west-1.amazonaws.com/s3fs-public/field-uploads/2k15StateFiles/NSDUHsaeShortTermCHG2015.htm"

drug_use_html = read_html(url)
```

```{r}
drug_use_html %>% 
  html_table() %>% 
  first() %>% 
  slice(-1)
```



### SW data

```{r}
url = "https://www.imdb.com/list/ls070150896/"

swm_html = read_html(url)
```


How do I get the stuff I want

```{r}
sw_titles =
  swm_html %>% 
  html_elements(".lister-item-header a") %>% 
  html_text()

sw_runtime = 
  swm_html %>% 
  html_elements(".runtime") %>% 
  html_text()

sw_money = 
  swm_html %>% 
  html_elements(".text-muted .ghost~ .text-muted+ span") %>% 
  html_text()

sw_df = 
  tibble(
    title = sw_titles,
    runtime = sw_runtime,
    money = sw_money
  )
```


## APIs

```{r}
water_df = 
  GET("https://data.cityofnewyork.us/resource/ia2d-e54m.csv") %>% 
  content("parsed")
```


```{r}
brfss_df = 
  GET("https://chronicdata.cdc.gov/resource/acme-vg9e.csv",
      query = list("$limit" = 5000)) %>% 
  content("parsed")
```

pokemon

```{r}
poke = 
  GET("http://pokeapi.co/api/v2/pokemon/1") %>%
  content()

names(poke)

poke[["stats"]]
```

